{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-sns.fullname" . }}-secret
  labels:
    {{- include "ai-sns.labels" . | nindent 4 }}
type: Opaque
data:
  DB_HOST: {{ .Values.database.host | b64enc | quote }}
  DB_PORT: {{ .Values.database.port | toString | b64enc | quote }}
  DB_USER: {{ .Values.database.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  DB_NAME: {{ .Values.database.name | b64enc | quote }}
{{- end }}
